name: Deploy Next.js

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy ECS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.ECS_HOST }}
                  username: ${{ secrets.ECS_USERNAME }}
                  key: ${{ secrets.ECS_SSH_KEY }}

                  script: |
                        cd /opt/build-own-vocabulary
  
                        git clean -fd
                        git pull origin main
                        
                        # Force remove any remaining containers and free resources
                        docker compose down -v --remove-orphans
                        
                        # Give system time to release ports
                        sleep 2
                        
                        docker compose up -d --build